title: Amy Penuela
logo: /assets/img/IMG_5078.PNG
description: Computer Science Bachelor | Passionate about Tech and Innovation | Ready to Contribute to the Digital World
#show_downloads: true
theme: jekyll-theme-minimal

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
