title: Amy Penuela
logo: /assets/img/IMG_5078.PNG
description: Computer Science Bachelor | Passionate about Tech and Innovation | Ready to Contribute to the Digital World
#show_downloads: true
theme: jekyll-theme-minimal
